name: Custom build for jerzh.github.io

on:
  push:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Webpack doesn't work (yet) with Node 17
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install deps
        run: npm install

      - name: Run build script
        run: npm run build
