name: Deploy Jekyll site (with Node) to Pages

on:
  push:
    branches: ["gh-pages"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          # Webpack doesn't work (yet) with Node 17
          node-version: "16.x"

      - name: Install deps
        run: npm install

      - name: Run build script
        run: npm run build

      # Jekyll/Pages stuff
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: '3.0'

          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true 

          # Increment this number if you need to re-download cached gems
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1

      # defaults output to '/_site'
      - run: bundle exec jekyll build --baseurl ${{ steps.pages.outputs.base_path }}

      - name: Upload artifact
        # This will automatically upload an artifact from the '/_site' directory
        uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
